### ISSUE TITLE
no variant or associated item named `TimeOut` found for enum `curerr::CursedError` in the current scope

### ISSUE THREAD

**Issue by zhengxingjian** [CURVoid/cursock#1]
no variant or associated item named `TimeOut` found for enum `curerr::CursedError` in the current scope

**Comment by 402status** [comment]
thanks for writing down about this issue, `curerr` crate was updated and version `cursock` previously used was yanked, now there really isn't any TimeOut item for enum curerr::CursedError, you should just wait for this bug fix

**Comment by CURVoid** [comment]
this issue is fixed now with 1.2.3 by removing `curerr` crate and using std::io::Error, thanks for writing down about this issue!

**Comment by 402status** [comment]
this issue is fixed now with 1.2.3 by removing curerr crate and using std::io::Error, thanks for writing down about this issue!
